apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner-role
rules:
  - apiGroups: ["objectstorage.k8s.io"]
    resources: ["buckets", "bucketaccesses","buckets/status", "bucketaccesses/status", "bucketaccessclasses", "bucketaccessclasses/status", "bucketclaims", "bucketclaims/status"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: objectstorage-provisioner-role
subjects:
- kind: ServiceAccount
  name: objectstorage-provisioner-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
stringData:
  ACCESS_KEY: {{ required "access_key is required." .Values.secret.access_key | quote }}
  ACCOUNT_NAME: {{ .Values.account_name | quote }}
  ENDPOINT: {{ required "endpoint is required." .Values.secret.endpoint | quote }}
  PC_SECRET: {{ required "pc_secret is required." .Values.secret.pc_secret | quote }}
  SECRET_KEY: {{ required "secret_key is required." .Values.secret.secret_key | quote }}
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 8 }}
      labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 8 }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: objectstorage-provisioner
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: cosi-driver-nutanix
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
      - name: objectstorage-provisioner-sidecar
        image: "{{ .Values.objectstorageProvisionerSidecar.image.registry }}/{{ .Values.objectstorageProvisionerSidecar.image.repository }}:{{ .Values.objectstorageProvisionerSidecar.image.tag }}"
        imagePullPolicy: {{ .Values.objectstorageProvisionerSidecar.image.pullPolicy }}
        args:
          - "--v={{ .Values.objectstorageProvisionerSidecar.logLevel }}"
        envFrom:
          - secretRef:
              name: objectstorage-provisioner
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /var/lib/cosi
            name: socket
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - emptyDir: {}
        name: socket
