apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
    - name: awscli
      # TODO: Replace the image with an official one once Amazon publishes theirs
      image: pknutanix/aws-cli:1.16.220
      stdin: true
      tty: true
      volumeMounts:
        - name: cosi-secrets
          mountPath: /data/cosi
  volumes:
  - name: cosi-secrets
    secret:
      secretName: bucketcreds
