kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: sample-bc
provisioner: ntnx.objectstorage.k8s.io
isDefaultBucketClass: true
allowedNamespaces:
- default
protocol:
  s3:
    region: us-east-1
    signatureVersion: S3V4
deletionPolicy: Delete
