---
apiVersion: v1
kind: Namespace
metadata:
  name: ntnx-system
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
