---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosi-driver-nutanix
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses","buckets/status", "bucketaccesses/status", "bucketaccessclasses", "bucketaccessclasses/status", "bucketclaims", "bucketclaims/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs: ["get", "delete", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosi-driver-nutanix
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
subjects:
  - kind: ServiceAccount
    name: cosi-driver-nutanix
    namespace: default # must set to default. see https://github.com/kubernetes-sigs/kustomize/issues/1377#issuecomment-694731163
roleRef:
  kind: ClusterRole
  name: cosi-driver-nutanix
  apiGroup: rbac.authorization.k8s.io
