apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
type: Opaque
stringData:
  # Nutanix Object Store instance endpoint, eg. "http://10.51.142.82:80"
  ENDPOINT: "<ENDPOINT>"
  # Admin IAM Access key to be used for Nutanix Objects
  ACCESS_KEY: "<ACCESS_KEY>"
  # Admin IAM Secret key to be used for Nutanix Objects
  SECRET_KEY: "<SECRET_KEY>"
  # Prism Central endpoint, eg. "https://10.51.149.82:9440"
  PC_ENDPOINT: "<ENDPOINT>"
  # PC Credentials in format <user>:<password>. 
  # eg. "user:password"
  PC_SECRET: "<USER>:<PASSWORD>"
  # Controls whether certificate chain will be validated for S3 endpoint
  # If INSECURE is set to true, an insecure connection will be made with
  # the S3 endpoint (Certs will not be used)
  S3_INSECURE: "false"
  # Controls whether certificate chain will be validated for Prism Central
  # If INSECURE is set to true, an insecure connection will be made with
  # the PC endpoint (Certs will not be used)
  PC_INSECURE: "false"
  # Base64 encoded content of the root certificate authority file for S3 endpoint
  # empty if no certs should be used.
  # Example, 
  # S3_CA_CERT: "LS0tLS1CRU...SUZJQ0FURS0tLS0tCg=="
  S3_CA_CERT: ""
  # Base64 encoded content of the root certificate authority file for Prism Central
  # empty if no certs should be used.
  PC_CA_CERT: ""
  # Account Name is a displayName identifier Prefix for Nutanix 
  # Objects to ensure that multiple requests for the same account
  # result in only one access token being created
  # (Default_Prefix: ntnx-cosi-iam-user)
  ACCOUNT_NAME: ""
