apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ntnx
type: Opaque
stringData:
  # Nutanix Object Store instance endpoint, eg. "http://10.51.142.82:80"
  ENDPOINT: "<ENDPOINT>"
  # Admin IAM Access key to be used for Nutanix Objects
  ACCESS_KEY: "<ACCESS_KEY>"
  # Admin IAM Secret key to be used for Nutanix Objects
  SECRET_KEY: "<SECRET_KEY>"
  # PC Credentials in format <prism-ip>:<prism-port>:<user>:<password>. 
  # eg. "10.51.142.125:9440:user:password"
  PC_SECRET: "<PRISM-IP>:<PRISM-PORT>:<USER>:<PASSWORD>"
  # CA Cert for Object Store endpoint TLS in b64 encoded format
  # empty if no certs should be used.
  CA_CERT: ""
  # Account Name is a displayName identifier Prefix for Nutanix 
  # Objects to ensure that multiple requests for the same account
  # result in only one access token being created
  # (Default_Prefix: ntnx-cosi-iam-user)
  ACCOUNT_NAME: ""