apiVersion: v1
kind: Pod
metadata:
  name: objects-triton
  labels:
    app: objects-triton
spec:
  containers:
  - name: objects-triton
    image: objects-triton:debug
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 7200
    - name: https
      containerPort: 7201
    - name: iam-mock
      containerPort: 5556
    env:
    - name: ACCEPT_EULA
      value: "Y"
    volumeMounts:
    - name: triton-data
      mountPath: /home/nutanix/data
    securityContext:
      privileged: true
  volumes:
  - name: triton-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: objects-triton-svc
spec:
  type: NodePort
  selector:
    app: objects-triton
  ports:
  - name: http
    port: 80
    targetPort: 7200
    nodePort: 30720
  - name: https
    port: 443
    targetPort: 7201
    nodePort: 30721
  - name: iam-mock
    port: 5556
    targetPort: 5556
    nodePort: 30556