FROM gcr.io/distroless/static:latest
LABEL maintainers="Nutanix COSI Authors"
LABEL description="Nutanix COSI driver"
COPY ./bin/cosi-driver-nutanix cosi-driver-nutanix
ENTRYPOINT ["/cosi-driver-nutanix"]
