name: Generate release artefact

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get repository name
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "^1.19"

    - name: Install tools
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: "github"
        kustomize: "latest"
        ko: "latest"

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: capi-nutanix
        sep-tags: ","
        sep-labels: ","
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha

    - name: Build container
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        TAGS: ${{ steps.meta.outputs.tags }}
        LABELS: ${{ steps.meta.outputs.labels }}
        PLATFORMS: linux/amd64,linux/arm64,linux/arm
      run: |
        PTAGS=`echo $TAGS | sed 's/capi-nutanix://g'`
        export SOURCE_DATE_EPOCH=$(date +%s)
        ko build --bare --image-label "$LABELS" -t "$PTAGS" --platform=$PLATFORMS ./cmd/${{ env.REPOSITORY_NAME }}
